import { Platform, TextStyle } from 'react-native';

const fontFamily = Platform.select({
  ios: 'System',
  android: 'Roboto',
}) as string;

export const colors = {
  primary: '#F5B800',
  onPrimary: '#000000',
  primaryLight: '#FFD700',
  primaryDark: '#CC9400',

  background: '#FFFFFF',
  surface: '#F2F2F7',
  surfaceElevated: '#FFFFFF',

  onSurface: '#000000',
  onSurfaceSecondary: '#8E8E93',
  onSurfaceTertiary: '#C7C7CC',

  separator: '#C6C6C8',
  separatorOpaque: '#E5E5E5',

  success: '#34C759',
  warning: '#FF9500',
  error: '#FF3B30',
  info: '#007AFF',

  tint: '#F5B800',
  tintSecondary: '#8E8E93',

  groupedBackground: '#F2F2F7',
  white: '#FFFFFF',
  black: '#000000',
};

export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};

export const borderRadius = {
  sm: 4,
  md: 8,
  lg: 12,
  xl: 16,
  full: 9999,
};

type TypographyStyle = TextStyle;

export const typography: Record<string, TypographyStyle> = {
  largeTitle: {
    fontFamily: fontFamily,
    fontSize: 34,
    fontWeight: '700',
    letterSpacing: 0.37,
  },
  title1: {
    fontFamily: fontFamily,
    fontSize: 28,
    fontWeight: '700',
    letterSpacing: 0.36,
  },
  title2: {
    fontFamily: fontFamily,
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: 0.35,
  },
  title3: {
    fontFamily: fontFamily,
    fontSize: 20,
    fontWeight: '600',
    letterSpacing: 0.38,
  },
  headline: {
    fontFamily: fontFamily,
    fontSize: 17,
    fontWeight: '600',
    letterSpacing: -0.41,
  },
  body: {
    fontFamily: fontFamily,
    fontSize: 17,
    fontWeight: '400',
    letterSpacing: -0.41,
  },
  callout: {
    fontFamily: fontFamily,
    fontSize: 16,
    fontWeight: '400',
    letterSpacing: -0.32,
  },
  subhead: {
    fontFamily: fontFamily,
    fontSize: 15,
    fontWeight: '400',
    letterSpacing: -0.24,
  },
  footnote: {
    fontFamily: fontFamily,
    fontSize: 13,
    fontWeight: '400',
    letterSpacing: -0.08,
  },
  caption1: {
    fontFamily: fontFamily,
    fontSize: 12,
    fontWeight: '400',
    letterSpacing: 0,
  },
  caption2: {
    fontFamily: fontFamily,
    fontSize: 11,
    fontWeight: '400',
    letterSpacing: 0.07,
  },
  button: {
    fontFamily: fontFamily,
    fontSize: 17,
    fontWeight: '600',
    letterSpacing: -0.41,
  },
};

export const shadows = {
  sm: {
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  md: {
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  lg: {
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
};

export const hitSlop = {
  top: 8,
  bottom: 8,
  left: 8,
  right: 8,
};

export const icons = {
  home: 'home',
  search: 'search',
  cart: 'cart',
  person: 'person',
  menu: 'menu',
  chevronForward: 'chevron-forward',
  chevronBack: 'chevron-back',
  add: 'add',
  remove: 'remove',
  checkmark: 'checkmark',
  close: 'close',
  settings: 'settings',
  notifications: 'notifications',
  star: 'star',
  starHalf: 'star-half',
  location: 'location',
  call: 'call',
  mail: 'mail',
  calendar: 'calendar',
  time: 'time',
  camera: 'camera',
  image: 'image',
  refresh: 'refresh',
  share: 'share',
  heart: 'heart',
  heartOutline: 'heart-outline',
  trash: 'trash',
  create: 'create',
  document: 'document',
  folder: 'folder',
  download: 'download',
  cloud: 'cloud',
  cloudDone: 'cloud-done',
  cloudOff: 'cloud-off',
  sync: 'sync',
  help: 'help',
  info: 'information-circle',
  warning: 'warning',
  alert: 'alert-circle',
  checkCircle: 'checkmark-circle',
  radioButtonOn: 'radio-button-on',
  square: 'square',
  squareOutline: 'square-outline',
  flag: 'flag',
  bookmark: 'bookmark',
  bookmarkOutline: 'bookmark-outline',
  list: 'list',
  grid: 'grid',
  layers: 'layers',
  apps: 'apps',
  phonePortrait: 'phone-portrait',
  tabletPortrait: 'tablet-portrait',
  laptop: 'laptop',
  watch: 'watch',
  fitness: 'fitness',
  restaurant: 'restaurant',
  wine: 'wine',
  cafe: 'cafe',
  cartOutline: 'cart-outline',
  basket: 'basket',
  pricetag: 'pricetag',
  cash: 'cash',
  card: 'card',
  wallet: 'wallet',
  receipt: 'receipt',
  print: 'print',
  cellular: 'cellular',
  wifi: 'wifi',
  bluetooth: 'bluetooth',
  gps: 'navigate',
  map: 'map',
  navigate: 'navigate',
  personAdd: 'person-add',
  personRemove: 'person-remove',
  people: 'people',
  peopleOutline: 'people-outline',
  happy: 'happy',
  sad: 'sad',
  bus: 'bus',
  car: 'car',
  train: 'train',
  airplane: 'airplane',
  boat: 'boat',
  bicycle: 'bicycle',
  footSteps: 'footsteps',
  shield: 'shield',
  lockClosed: 'lock-closed',
  lockOpen: 'lock-open',
  key: 'key',
  hammer: 'hammer',
  construct: 'construct',
  hammerOutline: 'construct-outline',
  body: 'body',
  cut: 'cut',
  medical: 'medical',
  fitnessOutline: 'fitness-outline',
  eye: 'eye',
  eyeOff: 'eye-off',
  visibility: 'visibility',
  visibilityOff: 'visibility-off',
  lock: 'lock-closed',
  unlock: 'lock-open',
  browse: 'globe',
  link: 'link',
  unlink: 'link-outline',
  attach: 'attach',
  shareSocial: 'share-social',
  socialTwitter: 'logo-twitter',
  socialFacebook: 'logo-facebook',
  socialInstagram: 'logo-instagram',
  socialGithub: 'logo-github',
  socialGoogle: 'logo-google',
  socialApple: 'logo-apple',
  quantizer: 'calculator',
  trendingUp: 'trending-up',
  trendingDown: 'trending-down',
  trendingFlat: 'trending-flat',
  pin: 'pin',
  pinOutline: 'pin-outline',
  navigateCircle: 'navigate-circle',
  code: 'code',
  codeSlash: 'code-slash',
  terminal: 'terminal',
  bug: 'bug',
  build: 'build',
  flash: 'flash',
  flashOff: 'flash-off',
  moon: 'moon',
  moonOutline: 'moon-outline',
  sunny: 'sunny',
  sunnyOutline: 'sunny-outline',
  globe: 'globe',
  leaf: 'leaf',
  leafOutline: 'leaf-outline',
  flower: 'flower',
  flowerOutline: 'flower-outline',
  paw: 'paw',
  pawOutline: 'paw-outline',
  earth: 'earth',
  earthOutline: 'earth-outline',
};

export default {
  colors,
  spacing,
  borderRadius,
  typography,
  shadows,
  hitSlop,
  icons,
};